import type { PageComponent } from 'types'

import Head from 'next/head'
import useSWR from 'swr'
import { SimpleGrid, Flex, Box, Heading, useColorModeValue } from '@chakra-ui/react'
import { getLayout } from 'src/layouts/MainLayout'

import { useUser, fetcher } from 'src/lib/hooks'

const HomePage: PageComponent = () => {
  const { data: { users } = {} } = useSWR('/api/users', fetcher)
  const tileBgColor = useColorModeValue('blue.200', 'blue.600')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading as="h2" my="4">
        All users
      </Heading>

      {!!users?.length && (
        <SimpleGrid columns={[2, null, 3]} spacing="8" mx="40">
          {users.map((user) => (
            <Box
              key={user.username}
              bg={tileBgColor}
              p="2"
              overflowX="scroll"
              borderRadius="32"
              borderColor="red.400"
              borderWidth="4px"
            >
              <pre>{JSON.stringify(user, null, 2)}</pre>
            </Box>
          ))}
        </SimpleGrid>
      )}
    </>
  )
}

HomePage.getLayout = getLayout

export default HomePage
