import type { PageComponent } from 'types'

import Head from 'next/head'
import { Stack, Heading } from '@chakra-ui/react'

import { getLayout } from 'src/layouts/MainLayout'
import UsersGrid from 'src/components/UsersGrid'
import useUsers from 'src/hooks/useUsers'

const HomePage: PageComponent = () => {
  const { data: users } = useUsers()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!!users?.length ? (
        <Stack align="center" mx={{ base: 'none', md: '40' }}>
          <Heading as="h2" my="4">
            All Users
          </Heading>
          <UsersGrid users={users} />
        </Stack>
      ) : (
        <Heading as="h2">No Users Found 😟</Heading>
      )}
    </>
  )
}

HomePage.getLayout = getLayout

export default HomePage
